---
title: "Risk Mitigation Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: journal
    css: custom.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(networkD3)
# If needed run once from the Console
# install.packages("DT")
library(readr)
Risks <- read_csv("https://raw.githubusercontent.com/AlanBerg/LSAC-2018/cb65e9efba522b872615ec1bad682ec0d85cd89e/Groups/RiskMitigation/Risks.csv")
Websites <- read_csv("https://raw.githubusercontent.com/AlanBerg/LSAC-2018/master/Groups/RiskMitigation/URL.csv")

# Color codes
# https://htmlcolorcodes.com
```

Overview
=====================================

```{r}
URL <- paste0(
        "graphdata.json")

## Convert to list format
Flare <- jsonlite::fromJSON(URL, simplifyDataFrame = FALSE)

# Use subset of data for more readable diagram
#Flare$children = Flare$children[1:3]

radialNetwork(List = Flare, fontSize = 11, opacity = 0.9, fontFamily = 'News Cycle')
```


Top 10 
=====================================  

### TOP TEN LIST


```{r child = 'Fragments/Description.md'}
# Add a text fragment
```

### Key points to note

```{r child = 'Fragments/REF-1.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-2.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-3.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-4.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-5.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-6.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-7.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-8.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-9.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-10.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-11.md'}
# Add a text fragment
```


```{r child = 'Fragments/REF-12.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-13.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-14.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-15.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-16.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-17.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-18.md'}
# Add a text fragment
```

```{r child = 'Fragments/REF-19.md'}
# Add a text fragment
```


```{r child = 'Fragments/Contact.md'}
# Add a text fragment
```


```{r child = 'Fragments/Process.md'}
# Add a text fragment
```


```{r child = 'Fragments/Gabor-Ref-20-53.md'}
# Add a text fragment
```

Searchable Library {data-navmenu="Library"}
===================================== 

### Search and print

```{r}
DT::datatable(Risks, extensions = 'Buttons',editable = TRUE, rownames = FALSE, options = list(
    dom = 'Bfrtip',
    colReorder = TRUE,
    keys = TRUE,
    rowReorder = TRUE,
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)
```

Websites {data-navmenu="Library"}
===================================== 

### Intersting online sources

```{r}
DT::datatable(Websites, extensions = 'Buttons',editable = TRUE, rownames = FALSE, options = list(
    dom = 'Bfrtip',
    colReorder = TRUE,
    keys = TRUE,
    rowReorder = TRUE,
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)
```



Resources {data-navmenu="Help"}
===================================== 

### Information



